### PR TITLE
Update membership-expectations.md

### PR DESCRIPTION
**Pull request by meyerweb**

### CODE REVIEW

**Comment by bkardell** [comment]
Yes, please.

**Comment by Elchi3** [comment]
Per our membership expectations, "alternate members are approved on the basis of consensus in steering committee meetings". So, I will formally ask for consensus in our call on Wednesday.

Happy to have you here, Eric! 🎉

**Review by robnyman — APPROVED** [review]

**Comment by robnyman** [comment]
Welcome @meyerweb!

**Review by chrisdavidmills — APPROVED** [review]
Nice!

**Review by Elchi3 — APPROVED** [review]
Everyone in today's SC call approved this!

Welcome again!

**Pull request merged**
