### PR TITLE
Update impact report to cover all of 2021

### PR DESCRIPTION
**Pull request by wbamberg**
This PR updates the impact report to cover all of 2021, rather than stopping in September.

What's here:

* extended the metrics through 2021, and updated the charts from https://docs.google.com/spreadsheets/d/1-7-jmrVCmsxb1adSujY8L5xxLIIV2MBTxL83AdW4Kfc/edit#gid=1905720905.
* reorganized "projects" into "Completed projects" and "Current projects". I think this gives us a better way to talk about things we've done, and things we haven't finished yet but are working on. This also means I've made it more project-centred, and less talking about general themes (like contributing to IA discussions, say).

I haven't replaced the "September" pie charts with "December". I could do if you like although it won't look so good, partly because December is just a weird month.

I'd encourage @Elchi3 , @estelle , and @teoli2003 to suggest improvements to my descriptions of their projects. Also tagging @robnyman and @torgo for review.

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
Looks good to me. Nice work, Will! 👍 

I think this wraps up 2021 nicely. I guess we will have to work out how to make this a continued/versioned report or is the idea to start with a somewhat empty 2022 report where we add things until this December?

**Comment by teoli2003** [comment]
Sounds good to me! Thanks a lot @wbamberg

**Review by teoli2003 — APPROVED** [review]

**Comment by wbamberg** [comment]
> Looks good to me. Nice work, Will! 👍

Thanks!

> I think this wraps up 2021 nicely. I guess we will have to work out how to make this a continued/versioned report or is the idea to start with a somewhat empty 2022 report where we add things until this December?

I think my plan is to write something for Q1 that just talks about staffing and the work we did (metrics + projects) and either make it standalone for each quarter or build on it in each quarter. This report contains a lot of content that's not directly about the work we did (i.e. financials, marketing quotes, mission) that I would not include in a quarterly update, but that we could put into a yearly report close to the end of 2022.

(I think at that point this quarterly report ends up looking a lot like a quarterly version of the worklog, and we might want to consider what the relation between these things is.)

**Comment by Elchi3** [comment]
> I think my plan is to write something for Q1 that just talks about staffing and the work we did (metrics + projects) and either make it standalone for each quarter or build on it in each quarter. This report contains a lot of content that's not directly about the work we did (i.e. financials, marketing quotes, mission) that I would not include in a quarterly update, but that we could put into a yearly report close to the end of 2022.

That sounds very reasonable to me.

> (I think at that point this quarterly report ends up looking a lot like a quarterly version of the worklog, and we might want to consider what the relation between these things is.)

My feeling is that we should then publish quarterly worklog blog posts that go hand in hand with the quarterly impact report. 

However, if we believe there should be monthly updates, I would propose to change the monthly blog posts to something different. The 2021 worklog format hasn't been the most interesting. (at least that's the feedback I heard). We could challenge ourselves to publish a blog post once a month on a particular topic about doc writing or a deep dive on a project we did or want to do.

**Comment by teoli2003** [comment]
I like the idea of publishing a monthly blog post about subject (like Migrating to markdown, How to document events, Aria and documentation). These could (in the future) be published on the future OWD website that can then have content.

Each of these blog posts will also have a clear owner.

/me really likes this.

**Comment by Elchi3** [comment]
Merging this for now. Let us know if there are further comments / things to improve.

**Comment by robnyman** [comment]
A few weeks too late, but looks great! Thanks for updating the report!

**Pull request merged**
