### PR TITLE
Add steering committee membership expectations

### PR DESCRIPTION
**Pull request by Elchi3**
- Adds a new folder `steering-committee/ ` 
- Adds SC membership expectation doc

### CODE REVIEW

**Review by jorydotcom — APPROVED** [review]
Can we add a 'Signatures' section or similar to indicate our intent for SC members to sign via PR?

**Comment by Elchi3** [comment]
> Can we add a 'Signatures' section or similar to indicate our intent for SC members to sign via PR?

Thanks! Added a "Signing members" section

**Comment by Elchi3** [comment]
> SC members to sign via PR?

Robert signed in here. So either everyone does that as well, or I merge this and we ask everyone to open their own PRs to sign. Thoughts?

**Comment by dontcallmedom** [comment]
would be happy to signed in w3c's name if I had write access to the repo :)

**Comment by Elchi3** [comment]
Please open PRs to sign this doc :)

**Pull request merged**
